In [1]:
import numpy as np
from src.fk.forward_kinematics import forward_kinematics
from src.utils.utils import screw_axis

## Example 1

In [2]:
M = np.array([[1, 0, 0, 0.5],  # Replace with actual values
              [0, 1, 0, 0],
              [0, 0, 1, 0.1],
              [0, 0, 0, 1]])
S1 = [0, 0, 1, 0, 0, 0]  # Screw axis for joint 1
S2 = [0, 1, 0, -0.1, 0, 0]  # Screw axis for joint 2
S = [S1, S2]

q = [np.pi/4, np.pi/6]  # Example joint angles
T_end_effector = forward_kinematics(M, S, q)
print("End-Effector Transformation Matrix:\n", np.round(T_end_effector, 2))

End-Effector Transformation Matrix:
 [[ 0.61 -0.71  0.35  0.31]
 [ 0.61  0.71  0.35  0.31]
 [-0.5   0.    0.87 -0.15]
 [ 0.    0.    0.    1.  ]]


## Example 2

In [3]:

# joint angle vector (1)
jt_list=list("RRR")
n_joints = len(jt_list)

# Define the link lengths and offsets
l1, l2, l3 = 1.0, 1.0, 1.0

# Home configuration matrix (2)
M = np.eye(4)
M[0, 3] = l1 + l2 + l3

# Define the arbitrary points on the joint axes at zero configuration (3)
a1 = np.array([0, 0, 0])  # Base of the first link
a2 = np.array([l1, 0, 0]) # End of the first link, base of the second
a3 = np.array([l1 + l2, 0, 0]) # End of the second link, base of the third

a = np.array([a1, a2, a3])

# Define the rotational parts of the screw axes (4)
omega1 = np.array([0, 0, 1])
omega2 = np.array([0, 0, 1])
omega3 = np.array([0, 0, 1])

omega = np.array([omega1, omega2, omega3])

#####################################################################################

# Combine omega and v to create the full screw axis for each joint
S = []
for i in range(n_joints):
  S_i = screw_axis(omega[i], a[i], jt_list[i])

  S.append(S_i)
##########################################################


# Define q as symbolic or as specific values
q= [0.5, 1.0, 1.5]  # Using radians
# Calculate the transformation matrix (5)
T_end_effector = forward_kinematics(M, S, q)
print("End-Effector Transformation Matrix:\n", np.round(T_end_effector, 2))


End-Effector Transformation Matrix:
 [[-0.99 -0.14  0.   -0.04]
 [ 0.14 -0.99  0.    1.62]
 [ 0.    0.    1.    0.  ]
 [ 0.   -0.    0.    1.  ]]


## Example 3

In [4]:
# joint angle vector (1)
jt_list=list("RRRRRR")
n_joints = len(jt_list)

# Define the link lengths and offsets
L1, L2, H1, H2, W1, W2 = (425, 392, 89, 95, 109, 82)  # All values in mm

# Home configuration matrix (2)
M = np.array([
    [1, 0, 0, -L1 - L2],
    [0, 0, -1, -W1 - W2],
    [0, 1, 0, H1 - H2],
    [0, 0, 0, 1]
])
# Define the arbitrary points on the joint axes at zero configuration (3)
a1 = np.array([0, 0, 0])
a2 = np.array([0, 0, H1])
a3 = np.array([-L1, 0, H1])
a4 = np.array([-L1 - L2, 0, H1])
a5 = np.array([-L1 - L2, -W1, 0])
a6 = np.array([-L1 - L2, 0, H1 - H2])

a = np.array([a1, a2, a3, a4, a5, a6])

# Define the rotational parts of the screw axes (4)
omega1 = np.array([0, 0, 1])
omega2 = np.array([0, -1, 0])
omega3 = np.array([0, -1, 0])
omega4 = np.array([0, -1, 0])
omega5 = np.array([0, 0, -1])
omega6 = np.array([0, -1, 0])

omega = np.array([omega1, omega2, omega3, omega4, omega5, omega6])

#####################################################################################


# Combine omega and v to create the full screw axis for each joint
S = []
for i in range(n_joints):
  S_i = screw_axis(omega[i], a[i], jt_list[i])

  S.append(S_i)
##########################################################


# Define q as symbolic or as specific values
q= [0, -np.pi/2, 0, 0, np.pi/2, 0]  # Using radians

# Calculate the transformation matrix (5)
T_end_effector = forward_kinematics(M, S, q)
print("End-Effector Transformation Matrix:\n", np.round(T_end_effector, 2))



End-Effector Transformation Matrix:
 [[   0.    1.    0.  -95.]
 [  -1.    0.    0. -109.]
 [  -0.    0.    1.  988.]
 [   0.   -0.   -0.    1.]]


## Example 4


In [5]:

# joint angle vector (1)
jt_list=list("RRPR")
n_joints = len(jt_list)

# Define the link lengths and offsets
l1, l2, l0 = (325, 225, 46)  # All values in mm

# Home configuration matrix (2)
M = np.array([
    [1, 0, 0, l1 + l2],
    [0, -1, 0, 0],
    [0, 0, -1, l0],
    [0, 0, 0, 1]
])
# Define the arbitrary points on the joint axes at zero configuration (3)
a1 = np.array([0, 0, 0])
a2 = np.array([l1, 0, 0])
a3 = np.array([0, 0,0])
a4 = np.array([l1+l2, 0, 0])


a = np.array([a1, a2, a3, a4])

# Define the rotational parts of the screw axes (4)
omega1 = np.array([0, 0, 1])
omega2 = np.array([0, 0, 1])
v_s3 = np.array([0, 0, 1])
omega4 = np.array([0, 0, -1])


omega_v = np.array([omega1, omega2, v_s3, omega4])

#####################################################################################


# Combine omega and v to create the full screw axis for each joint
S = []
for i in range(n_joints):
  S_i = screw_axis(omega_v[i], a[i], jt_list[i])

  S.append(S_i)
##########################################################


# Define q as symbolic or as specific values
q= [0, np.pi/2, 10, -np.pi/2]  # Using radians

# Calculate the transformation matrix (5)
T_end_effector = forward_kinematics(M, S, q)
print("End-Effector Transformation Matrix:\n", np.round(T_end_effector, 2))
##########################################################



End-Effector Transformation Matrix:
 [[ -1.   0.   0. 325.]
 [  0.   1.   0. 225.]
 [  0.   0.  -1.  56.]
 [ -0.   0.   0.   1.]]


## Example 5


In [6]:

# joint angle vector (1)
jt_list=list("RPPR")
n_joints = len(jt_list)

# Define the link lengths and offsets
l1, l2, l0 = (325, 225, 46)  # All values in mm

# Home configuration matrix (2)
M = np.array([
    [1, 0, 0, l1 + l2],
    [0, -1, 0, 0],
    [0, 0, -1, l0],
    [0, 0, 0, 1]
])
# Define the arbitrary points on the joint axes at zero configuration (3)
a1 = np.array([0, 0, 0])
a2 = np.array([l1, 0, 0])
a3 = np.array([0, 0,0])
a4 = np.array([l1+l2, 0, 0])


a = np.array([a1, a2, a3, a4])

# Define the rotational parts of the screw axes (4)
omega1 = np.array([0, 0, 1])
v_s2 = np.array([0, 0, 1])
v_s3 = np.array([0, 0, 1])
omega4 = np.array([0, 0, -1])


omega_v = np.array([omega1, v_s2, v_s3, omega4])

#####################################################################################


# Combine omega and v to create the full screw axis for each joint
S = []
for i in range(n_joints):
  S_i = screw_axis(omega_v[i], a[i], jt_list[i])

  S.append(S_i)
##########################################################


# Define q as symbolic or as specific values
q= [0, np.pi/2, 10, -np.pi/2]  # Using radians

# Calculate the transformation matrix (5)
T_end_effector = forward_kinematics(M, S, q)
print("End-Effector Transformation Matrix:\n", np.round(T_end_effector, 2))
##########################################################



End-Effector Transformation Matrix:
 [[  0.     1.     0.   550.  ]
 [  1.     0.     0.     0.  ]
 [  0.     0.    -1.    57.57]
 [  0.     0.     0.     1.  ]]


# Example 6


In [7]:

# joint angle vector (1)
jt_list=list("RR")
n_joints = len(jt_list)

# Define the link lengths and offsets
l1, l2 = (1, 1)  # All values in mm

# Home configuration matrix (2)
M = np.array([
    [1, 0, 0, l1 + l2],
    [0, 1, 0, 0],
    [0, 0, 1, 0],
    [0, 0, 0, 1]
])
# Define the arbitrary points on the joint axes at zero configuration (3)
a1 = np.array([0, 0, 0])
a2 = np.array([l1, 0, 0])



a = np.array([a1, a2])

# Define the rotational parts of the screw axes (4)
omega1 = np.array([0, 0, 1])
omega2 = np.array([0, 0, 1])


omega = np.array([omega1, omega2])

#####################################################################################


# Combine omega and v to create the full screw axis for each joint
S = []
for i in range(n_joints):
  S_i = screw_axis(omega[i], a[i], jt_list[i])

  S.append(S_i)
##########################################################


# Define q as symbolic or as specific values
q= [0, np.pi/2]  # Using radians

# Calculate the transformation matrix (5)
T_end_effector = forward_kinematics(M, S, q)
print("End-Effector Transformation Matrix:\n", np.round(T_end_effector, 2))
##########################################################



End-Effector Transformation Matrix:
 [[ 0. -1.  0.  1.]
 [ 1.  0.  0.  1.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]
