In [ ]:
# Author: Muhammed Elyamani
# Date: 30 / 01 / 2024
# Email: melya038@uottawa.ca
# Repo: https://github.com/WikiGenius/RoboticScrewTheoryToolkit

In [1]:
import numpy as np
from src.utils.utils import get_q_d_normalized, screw_axis
from src.inverse_kinematics.inverse_kinematics import inverse_kinematics
from src.fk.forward_kinematics import forward_kinematics


## Example usage 1

In [2]:
# Example usage 1

# joint angle vector (1)
jt_list=list("RR")
n_joints = len(jt_list)
# Define the matrix M as provided
M = np.array([
    [1, 0, 0, 2],
    [0, 1, 0, 0],
    [0, 0, 1, 0],
    [0, 0, 0, 1]
])

# screw axis for each joint
s1 = np.array([0, 0, 1, 0, 0, 0])
s2 = np.array([0, 0, 1, 0, -1, 0])

S = np.array([s1, s2])
##########################################################

# Given transformation matrix T_goal
T_goal = np.array([
    [-0.5, -0.866, 0, 0.366],
    [0.866, -0.5, 0, 1.366],
    [0, 0, 1, 0],
    [0, 0, 0, 1]
])

print(f"T_goal: {T_goal}")
# q_initial=np.random.ranf(n_joints)
# q_initial=np.zeros(n_joints)
q_initial=np.ones(n_joints) * 0.1
print(f"q_initial: {q_initial}")

q_d = inverse_kinematics(M, S, T_goal, q_initial)
# print(f"q_d: {q_d}")
print(f"q_d: {get_q_d_normalized(q_d)} rad")

T_goal: [[-0.5   -0.866  0.     0.366]
 [ 0.866 -0.5    0.     1.366]
 [ 0.     0.     1.     0.   ]
 [ 0.     0.     0.     1.   ]]
q_initial: [0.1 0.1]
q_d: [0.52 1.57] rad


## Example usage 2


In [3]:
# Example usage 2

# joint angle vector (1)
jt_list=list("RRR")
n_joints = len(jt_list)

# Define the link lengths and offsets
l1, l2, l3 = 1.0, 1.0, 1.0

# Home configuration matrix (2)
M = np.eye(4)
M[0, 3] = l1 + l2 + l3

# Define the arbitrary points on the joint axes at zero configuration (3)
a1 = np.array([0, 0, 0])  # Base of the first link
a2 = np.array([l1, 0, 0]) # End of the first link, base of the second
a3 = np.array([l1 + l2, 0, 0]) # End of the second link, base of the third

a = np.array([a1, a2, a3])

# Define the rotational parts of the screw axes (4)
omega1 = np.array([0, 0, 1])
omega2 = np.array([0, 0, 1])
omega3 = np.array([0, 0, 1])

omega = np.array([omega1, omega2, omega3])

#####################################################################################


# Calculate the translational components of the screw axis (v_s1, v_s2, v_s3)
# Calculate the screw axis
S = [screw_axis(omega[i], a[i], jt_list[i]) for i in range(n_joints)]
##########################################################


# Define q as symbolic or as specific values
q= [0.5, 1.0, 1.5]  # Using radians
# Calculate the transformation matrix (5)
T = forward_kinematics(M, S, q)
print(f"T: {np.round(T, 2)}")

T_sd = T
q_initial=np.ones(n_joints) * 0.1
print(f"q_initial: {q_initial}")
q_d = inverse_kinematics(M, S, T_sd, q_initial)
# print(f"q_d: {q_d}")
print(f"q_d: {get_q_d_normalized(q_d)}")

T: [[-0.99 -0.14  0.   -0.04]
 [ 0.14 -0.99  0.    1.62]
 [ 0.    0.    1.    0.  ]
 [ 0.   -0.    0.    1.  ]]
q_initial: [0.1 0.1 0.1]
q_d: [0.5 1.  1.5]


## Example usage 3

In [4]:
# Example usage 3

# joint angle vector (1)
jt_list=list("RRR")
n_joints = len(jt_list)

# Define the link lengths and offsets
l1, l2, l3 = 1.0, 1.0, 1.0

# Home configuration matrix (2)
M = np.eye(4)
M[0, 3] = l1 + l2 + l3

# Define the arbitrary points on the joint axes at zero configuration (3)
a1 = np.array([0, 0, 0])  # Base of the first link
a2 = np.array([l1, 0, 0]) # End of the first link, base of the second
a3 = np.array([l1 + l2, 0, 0]) # End of the second link, base of the third

a = np.array([a1, a2, a3])

# Define the rotational parts of the screw axes (4)
omega1 = np.array([0, 0, 1])
omega2 = np.array([0, 0, 1])
omega3 = np.array([0, 0, 1])

omega = np.array([omega1, omega2, omega3])

#####################################################################################


# Calculate the translational components of the screw axis (v_s1, v_s2, v_s3)
# Calculate the screw axis
S = [screw_axis(omega[i], a[i], jt_list[i]) for i in range(n_joints)]
##########################################################


# Define q as symbolic or as specific values
q= [5.76, 2.09, 0.52]  # Using radians
# Calculate the transformation matrix (5)
T = forward_kinematics(M, S, q)
print(f"T: {np.round(T, 2)}")

T_sd = T
q_initial=np.ones(n_joints) * 0.1
print(f"q_initial: {q_initial}")
q_d = inverse_kinematics(M, S, T_sd, q_initial)
# print(f"q_d: {q_d}")
print(f"q_d: {get_q_d_normalized(q_d)}")

T: [[-0.49 -0.87  0.    0.38]
 [ 0.87 -0.49  0.    1.37]
 [ 0.    0.    1.    0.  ]
 [ 0.    0.    0.    1.  ]]
q_initial: [0.1 0.1 0.1]
q_d: [1.57 4.19 2.61]


## Example usage 4

In [5]:
# Example usage 4

# joint angle vector (1)
jt_list=list("RRRR")
n_joints = len(jt_list)

# Define the link lengths and offsets
l1, l2, l3, l4 = 1.0, 1.0, 1.0, 1.0

# Home configuration matrix (2)
M = np.eye(4)
M[0, 3] = l1 + l2 + l3 + l4

# Define the arbitrary points on the joint axes at zero configuration (3)
a1 = np.array([0, 0, 0])  # Base of the first link
a2 = np.array([l1, 0, 0]) # End of the first link, base of the second
a3 = np.array([l1 + l2, 0, 0]) # End of the second link, base of the third
a4 = np.array([l1 + l2 + l3, 0, 0])

a = np.array([a1, a2, a3, a4])

# Define the rotational parts of the screw axes (4)
omega1 = np.array([0, 0, 1])
omega2 = np.array([0, 0, 1])
omega3 = np.array([0, 0, 1])
omega4 = np.array([0, 0, 1])

omega = np.array([omega1, omega2, omega3, omega4])

#####################################################################################


# Calculate the translational components of the screw axis (v_s1, v_s2, v_s3)
# Calculate the screw axis
S = [screw_axis(omega[i], a[i], jt_list[i]) for i in range(n_joints)]
##########################################################


# Define q as symbolic or as specific values
q= [0, -np.pi/2, 0, np.pi/2]  # Using radians
# Calculate the transformation matrix (5)
T = forward_kinematics(M, S, q)
print(f"T: {np.round(T, 2)}")

T_sd = T
q_initial=np.ones(n_joints) * 0.1
print(f"q_initial: {q_initial}")
q_d = inverse_kinematics(M, S, T_sd, q_initial)
# print(f"q_d: {q_d}")
print(f"q_d: {get_q_d_normalized(q_d)}")

T: [[ 1.  0.  0.  2.]
 [ 0.  1.  0. -2.]
 [ 0.  0.  1.  0.]
 [ 0. -0.  0.  1.]]
q_initial: [0.1 0.1 0.1 0.1]
q_d: [0.   4.71 0.   1.57]


## Example usage 5


In [6]:
# Example usage 5

# joint angle vector (1)
jt_list=list("RRRRRR")
n_joints = len(jt_list)

# Define the link lengths and offsets
L1, L2, H1, H2, W1, W2 = (0.425, 0.392, 0.089, 0.095, 0.109, 0.082)  # All values in m

# Home configuration matrix (2)
M = np.array([
    [1, 0, 0, -L1 - L2],
    [0, 0, -1, -W1 - W2],
    [0, 1, 0, H1 - H2],
    [0, 0, 0, 1]
])

# Define the arbitrary points on the joint axes at zero configuration (3)
a1 = np.array([0, 0, 0])
a2 = np.array([0, 0, H1])
a3 = np.array([-L1, 0, H1])
a4 = np.array([-L1 - L2, 0, H1])
a5 = np.array([-L1 - L2, -W1, 0])
a6 = np.array([-L1 - L2, 0, H1 - H2])

a = np.array([a1, a2, a3, a4, a5, a6])

# Define the rotational parts of the screw axes (4)
omega1 = np.array([0, 0, 1])
omega2 = np.array([0, -1, 0])
omega3 = np.array([0, -1, 0])
omega4 = np.array([0, -1, 0])
omega5 = np.array([0, 0, -1])
omega6 = np.array([0, -1, 0])

omega = np.array([omega1, omega2, omega3, omega4, omega5, omega6])

#####################################################################################


# Calculate the translational components of the screw axis (v_s1, v_s2, v_s3)
# Calculate the screw axis
S = [screw_axis(omega[i], a[i], jt_list[i]) for i in range(n_joints)]
##########################################################


# Define q as symbolic or as specific values
q= [0, -np.pi/2, 0, 0, np.pi/2, 0]  # Using radians
# Calculate the transformation matrix (5)
T = forward_kinematics(M, S, q)
print(f"T: {np.round(T, 2)}")

T_sd = T
q_initial=np.ones(n_joints) * 0.1
print(f"q_initial: {q_initial}")
q_d = inverse_kinematics(M, S, T_sd, q_initial)
# print(f"q_d: {q_d}")
print(f"q_d: {get_q_d_normalized(q_d)}")

T: [[ 0.    1.    0.   -0.1 ]
 [-1.    0.    0.   -0.11]
 [ 0.    0.    1.    0.99]
 [ 0.    0.    0.    1.  ]]
q_initial: [0.1 0.1 0.1 0.1 0.1 0.1]
q_d: [0.   4.69 0.04 6.26 1.57 0.  ]


## Example usage 6


In [7]:
# Example usage 6

# joint angle vector (1)
jt_list=list("RRPR")
n_joints = len(jt_list)

# Define the link lengths and offsets
l1, l2, l0 = (0.325, 0.225, 0.046)  # All values in m

# Home configuration matrix (2)
M = np.array([
    [1, 0, 0, l1 + l2],
    [0, -1, 0, 0],
    [0, 0, -1, l0],
    [0, 0, 0, 1]
])
# Define the arbitrary points on the joint axes at zero configuration (3)
a1 = np.array([0, 0, 0])
a2 = np.array([l1, 0, 0])
a3 = np.array([0, 0,0])
a4 = np.array([l1+l2, 0, 0])


a = np.array([a1, a2, a3, a4])

# Define the rotational parts of the screw axes (4)
omega1 = np.array([0, 0, 1])
omega2 = np.array([0, 0, 1])
v3 = np.array([0, 0, 1])
omega4 = np.array([0, 0, -1])


omega_v = np.array([omega1, omega2, v3, omega4])
#####################################################################################


# Calculate the translational components of the screw axis (v_s1, v_s2, v_s3)
# Calculate the screw axis
S = [screw_axis(omega[i], a[i], jt_list[i]) for i in range(n_joints)]
##########################################################


# Define q as symbolic or as specific values
q= [0, np.pi/2, 0.01, -np.pi/2]  # Using radians
# Calculate the transformation matrix (5)
T = forward_kinematics(M, S, q)
print(f"T: {np.round(T, 2)}")

T_sd = T
q_initial=np.ones(n_joints) * 0.1
print(f"q_initial: {q_initial}")
q_d = inverse_kinematics(M, S, T_sd, q_initial)
# print(f"q_d: {q_d}")
print(f"q_d: {get_q_d_normalized(q_d)}")

T: [[ 1.    0.    0.    0.32]
 [ 0.   -1.    0.   -0.01]
 [ 0.    0.   -1.    0.27]
 [ 0.    0.    0.    1.  ]]
q_initial: [0.1 0.1 0.1 0.1]
q_d: [0.   1.57 0.01 4.71]


In [8]:
# Example usage 6

# joint angle vector (1)
jt_list=list("PRPR")
n_joints = len(jt_list)

# Define the link lengths and offsets
l1, l2, l0 = (0.325, 0.225, 0.046)  # All values in m

# Home configuration matrix (2)
M = np.array([
    [1, 0, 0, l1 + l2],
    [0, -1, 0, 0],
    [0, 0, -1, l0],
    [0, 0, 0, 1]
])
# Define the arbitrary points on the joint axes at zero configuration (3)
a1 = np.array([0, 0, 0])
a2 = np.array([l1, 0, 0])
a3 = np.array([0, 0,0])
a4 = np.array([l1+l2, 0, 0])


a = np.array([a1, a2, a3, a4])

# Define the rotational parts of the screw axes (4)
v1 = np.array([1, 0, 0])
omega2 = np.array([0, 0, 1])
v3 = np.array([0, 0, 1])
omega4 = np.array([0, 0, 1])


omega_v = np.array([v1, omega2, v3, omega4])
#####################################################################################


# Calculate the translational components of the screw axis (v_s1, v_s2, v_s3)
# Calculate the screw axis
S = [screw_axis(omega_v[i], a[i], jt_list[i]) for i in range(n_joints)]
##########################################################


# Define q as symbolic or as specific values
q= [0.1, 0.5, 0.2, 0.2]  # Using radians & m
# Calculate the transformation matrix (5)
T = forward_kinematics(M, S, q)
print(f"T: {np.round(T, 2)}")

T_sd = T
q_initial=np.ones(n_joints) * 0.1
print(f"q_initial: {q_initial}")
q_d = inverse_kinematics(M, S, T_sd, q_initial)
# print(f"q_d: {q_d}")
print(f"q_d: {get_q_d_normalized(q_d)}")

T: [[ 0.76  0.64  0.    0.62]
 [ 0.64 -0.76  0.    0.11]
 [ 0.    0.   -1.    0.25]
 [ 0.    0.    0.    1.  ]]
q_initial: [0.1 0.1 0.1 0.1]
q_d: [0.1 0.5 0.2 0.2]
