In [1]:
import numpy as np
from src.utils.utils import screw_axis
from src.jacobian.space_jacobian import space_jacobian
from src.jacobian.calculate_twist import calculate_twist
from src.jacobian.calculate_joint_velocities import calculate_joint_velocities
from src.jacobian.analyze_jacobian import analyze_jacobian


## Calculate the space Jacobian


In [2]:
# Joint angle vector
jt_list = list("RRRRRR")
n_joints = len(jt_list)

# Define the link lengths and offsets
L1, L2, H1, H2, W1, W2 = (0.425, 0.392, 0.089, 0.095, 0.109, 0.082)  # All values in m

# Define the arbitrary points on the joint axes at zero configuration
a = np.array([[0, 0, 0],
              [0, 0, H1],
              [-L1, 0, H1],
              [-L1 - L2, 0, H1],
              [-L1 - L2, -W1, 0],
              [-L1 - L2, 0, H1 - H2]])

# Define the rotational parts of the screw axes
omega = np.array([[0, 0, 1],
                    [0, -1, 0],
                    [0, -1, 0],
                    [0, -1, 0],
                    [0, 0, -1],
                    [0, -1, 0]])

# Calculate the translational components of the screw axis
S = [screw_axis(omega[i], a[i], jt_list[i]) for i in range(n_joints)]


# Example joint angles (in radians)
q_list = [np.pi/4, np.pi/6, np.pi/3, 0, 0, np.pi/2]  # rad

# Calculate the space Jacobian
J = space_jacobian(S, q_list)
print("Space Jacobian J:\n", np.round(J, 2))


Space Jacobian J:
 [[ 0.    0.71  0.71  0.71  0.71  0.71]
 [ 0.   -0.71 -0.71 -0.71  0.71 -0.71]
 [ 1.    0.    0.    0.   -0.    0.  ]
 [ 0.    0.06 -0.09 -0.36  0.36 -0.36]
 [ 0.    0.06 -0.09 -0.36 -0.36 -0.36]
 [ 0.    0.    0.37  0.37  0.11  0.27]]


## Analyze the Jacobian

In [3]:
# Analyze the Jacobian
analysis = analyze_jacobian(J)
print("Determinant:", analysis['determinant'])
print("Rank:", analysis['rank'])
print("Is Singular:", analysis['is_singular'])


Determinant: 0.0
Rank: 5
Is Singular: True


## Calculate the twist

In [4]:
# Define joint velocities
q_dot = np.array([1, 1, 1, 1, 1, 1])  # rad / sec

# Calculate the twist
V_s = calculate_twist(J, q_dot)
print("For Joint velocities:", q_dot)
print("Twist (V_s):", np.round(V_s, 2))



For Joint velocities: [1 1 1 1 1 1]
Twist (V_s): [ 3.54 -2.12  1.   -0.39 -1.12  1.12]


## Calculate joint velocities for the given twist

In [5]:
# Calculate joint velocities for the given twist
q_dot_calculated = calculate_joint_velocities(J, V_s)
print("Joint Velocities (q_dot):", np.round(q_dot_calculated, 2))

Joint Velocities (q_dot): [1. 1. 1. 1. 1. 1.]
